### ISSUE TITLE
Add older versions to plugin

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview-covid19#11]
It would be helpful if older versions of the CORD19 database remain visible in the software

**Comment by bmkramer** [comment]
- In https://github.com/asreview/asreview-covid19/tree/master/datasets staan ook de eerdere versies van de datasets die we zelf uploaden (CORD vanaf dec 2019). Op termijn moeten we mss kijken of we die naar OSF zouden willen overzetten ivm github repo size?

- De 'grote' datasets halen we niet binnen, maar halen we direct van de link van Allen AI (= Amazon server). Als zij de datasets ook per versie archiveren op Zenodo zouden we ook daar naar kunnen verwijzen als persistente copy.

**Comment by J535D165** [comment]
Closing this issue because it is stale.
