### ISSUE TITLE
Update screenshot readme

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview-covid19#12]
Due to a new release of ASReview the screenshot in the Readme is outdated

**Comment by GerbrichFerdinands** [comment]
I took a new screenshot but I don't see the difference between this one and the screenshot that is currently in the readme. @Rensvandeschoot, what am I missing here?  

![127 0 0 1_5000_(iPad) (9)](https://user-images.githubusercontent.com/45358236/79433111-05c45e80-7fcd-11ea-8803-fec03717e1ba.png)

**Comment by GerbrichFerdinands** [comment]
![127 0 0 1_5000_(iPad Pro) (10)](https://user-images.githubusercontent.com/45358236/79434826-36a59300-7fcf-11ea-8826-89162aefcf18.png)

But then without a frame, so the CORD-19 dataset is visible?
