### ISSUE TITLE
Add badges to documentation

### ISSUE THREAD

**Issue by kequach** [asreview/asreview-covid19#43]
I would normally add a pull request but since there are already some badges further down in the repository I was unsure where you would like to add more badges. These help with visibility and therefore create more traffic to the repository. I would recommend to add a downloads badge and one for PyPi. The markdown for both you can find in the following code snippets:
`
[![Downloads](https://pepy.tech/badge/asreview-covid19)](https://pepy.tech/project/asreview-covid19)
`
`
[![PyPI version](https://badge.fury.io/py/asreview-covid19.svg)](https://badge.fury.io/py/asreview-covid19)
`
If you would like I can also create a pull request if you tell me where you would like to have the badges added.

**Comment by Rensvandeschoot** [comment]
I think it would be best to list all badges at the top of the page, so unless @J535D165 / @terrymyc  disagree, go ahead and do a PR.
